CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(320) NOT NULL,
    role_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    code VARCHAR(80) NOT NULL,
    contact_person VARCHAR(150),
    email VARCHAR(320),
    phone VARCHAR(50),
    address VARCHAR(500),
    city VARCHAR(120),
    state VARCHAR(120),
    country VARCHAR(120),
    lead_time_days INTEGER,
    capacity NUMERIC(19, 3),
    reliability_score NUMERIC(5, 2),
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_suppliers_code UNIQUE (code)
);

CREATE TABLE materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    category VARCHAR(120),
    unit VARCHAR(50),
    unit_cost NUMERIC(19, 2),
    criticality VARCHAR(50),
    current_stock NUMERIC(19, 3),
    safety_stock NUMERIC(19, 3),
    reorder_point NUMERIC(19, 3),
    daily_consumption NUMERIC(19, 3),
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_materials_code UNIQUE (code)
);

CREATE TABLE supplier_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    unit_price NUMERIC(19, 2),
    lead_time_days INTEGER,
    minimum_order_quantity NUMERIC(19, 3),
    maximum_capacity NUMERIC(19, 3),
    reliability_score NUMERIC(5, 2),
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_supplier_materials_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_supplier_materials_material FOREIGN KEY (material_id) REFERENCES materials (id),
    CONSTRAINT uk_supplier_materials_supplier_material UNIQUE (supplier_id, material_id)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    category VARCHAR(120),
    unit_cost NUMERIC(19, 2),
    selling_price NUMERIC(19, 2),
    production_time_hours NUMERIC(10, 2),
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_products_code UNIQUE (code)
);

CREATE TABLE product_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    quantity_required NUMERIC(19, 3) NOT NULL,
    unit VARCHAR(50),
    wastage_percentage NUMERIC(5, 2),
    CONSTRAINT fk_product_materials_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_product_materials_material FOREIGN KEY (material_id) REFERENCES materials (id),
    CONSTRAINT uk_product_materials_product_material UNIQUE (product_id, material_id)
);

CREATE TABLE inventories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT NOT NULL,
    warehouse_location VARCHAR(200) NOT NULL,
    quantity_on_hand NUMERIC(19, 3),
    quantity_reserved NUMERIC(19, 3),
    quantity_incoming NUMERIC(19, 3),
    safety_stock NUMERIC(19, 3),
    reorder_point NUMERIC(19, 3),
    last_updated TIMESTAMP,
    CONSTRAINT fk_inventories_material FOREIGN KEY (material_id) REFERENCES materials (id),
    CONSTRAINT uk_inventories_material_warehouse UNIQUE (material_id, warehouse_location)
);

CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number VARCHAR(80) NOT NULL,
    supplier_id BIGINT NOT NULL,
    order_date DATE,
    expected_delivery_date DATE,
    actual_delivery_date DATE,
    status VARCHAR(50),
    total_amount NUMERIC(19, 2),
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_purchase_orders_po_number UNIQUE (po_number),
    CONSTRAINT fk_purchase_orders_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_purchase_orders_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE TABLE purchase_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    quantity NUMERIC(19, 3) NOT NULL,
    unit_price NUMERIC(19, 2),
    expected_date DATE,
    received_quantity NUMERIC(19, 3),
    status VARCHAR(50),
    CONSTRAINT fk_purchase_order_items_purchase_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id),
    CONSTRAINT fk_purchase_order_items_material FOREIGN KEY (material_id) REFERENCES materials (id)
);

CREATE TABLE deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    tracking_number VARCHAR(120),
    dispatch_date DATE,
    expected_arrival_date DATE,
    actual_arrival_date DATE,
    status VARCHAR(50),
    delay_days INTEGER,
    notes VARCHAR(1000),
    CONSTRAINT fk_deliveries_purchase_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id)
);

CREATE TABLE supplier_performances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    evaluation_date DATE,
    on_time_delivery_rate NUMERIC(5, 2),
    average_delay_days NUMERIC(10, 2),
    lead_time_variance NUMERIC(10, 2),
    fulfillment_rate NUMERIC(5, 2),
    rejection_rate NUMERIC(5, 2),
    capacity_utilization NUMERIC(5, 2),
    disruption_count INTEGER,
    overall_score NUMERIC(5, 2),
    CONSTRAINT fk_supplier_performances_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT uk_supplier_performances_supplier_date UNIQUE (supplier_id, evaluation_date)
);

CREATE TABLE production_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_number VARCHAR(80) NOT NULL,
    product_id BIGINT NOT NULL,
    quantity NUMERIC(19, 3) NOT NULL,
    planned_start_date DATE,
    planned_end_date DATE,
    actual_start_date DATE,
    actual_end_date DATE,
    status VARCHAR(50),
    priority VARCHAR(50),
    created_by BIGINT,
    CONSTRAINT uk_production_orders_production_number UNIQUE (production_number),
    CONSTRAINT fk_production_orders_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_production_orders_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE TABLE customer_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(80) NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    order_date DATE,
    required_delivery_date DATE,
    status VARCHAR(50),
    priority VARCHAR(50),
    total_amount NUMERIC(19, 2),
    CONSTRAINT uk_customer_orders_order_number UNIQUE (order_number)
);

CREATE TABLE customer_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity NUMERIC(19, 3) NOT NULL,
    unit_price NUMERIC(19, 2),
    CONSTRAINT fk_customer_order_items_customer_order FOREIGN KEY (customer_order_id) REFERENCES customer_orders (id),
    CONSTRAINT fk_customer_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_users_role_id ON users (role_id);
CREATE INDEX idx_supplier_materials_supplier_id ON supplier_materials (supplier_id);
CREATE INDEX idx_supplier_materials_material_id ON supplier_materials (material_id);
CREATE INDEX idx_product_materials_product_id ON product_materials (product_id);
CREATE INDEX idx_product_materials_material_id ON product_materials (material_id);
CREATE INDEX idx_inventories_material_id ON inventories (material_id);
CREATE INDEX idx_purchase_orders_supplier_id ON purchase_orders (supplier_id);
CREATE INDEX idx_purchase_orders_created_by ON purchase_orders (created_by);
CREATE INDEX idx_purchase_order_items_purchase_order_id ON purchase_order_items (purchase_order_id);
CREATE INDEX idx_purchase_order_items_material_id ON purchase_order_items (material_id);
CREATE INDEX idx_deliveries_purchase_order_id ON deliveries (purchase_order_id);
CREATE INDEX idx_supplier_performances_supplier_id ON supplier_performances (supplier_id);
CREATE INDEX idx_production_orders_product_id ON production_orders (product_id);
CREATE INDEX idx_production_orders_created_by ON production_orders (created_by);
CREATE INDEX idx_customer_order_items_customer_order_id ON customer_order_items (customer_order_id);
CREATE INDEX idx_customer_order_items_product_id ON customer_order_items (product_id);

INSERT INTO roles (name, description)
VALUES
    ('ADMIN', 'System administrator'),
    ('SUPPLY_CHAIN_MANAGER', 'Supply chain operations manager'),
    ('PROCUREMENT_OFFICER', 'Procurement operations user');
